# Generated by Django 5.2.8 on 2025-11-30 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
