# Generated by Django 5.2.8 on 2025-11-30 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_address_line_address_street_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='Address',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
