# Generated by Django 5.2.8 on 2025-12-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_address_table_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='ward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
