# Generated by Django 5.2.8 on 2025-12-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_address_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ward',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
