# Generated by Django 5.2.8 on 2025-12-02 02:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_table_alter_product_table_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='products',
            new_name='product',
        ),
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('user', 'product')},
        ),
    ]
