# Generated by Django 5.2.8 on 2025-11-30 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_productimage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='ProductImage',
        ),
    ]
